services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cookbook
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
  adminer:
    profiles:
      - full
      - adminer
    image: adminer
    ports:
      - 3001:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: dracula
  api:
    build:
      context: ./api
      # dockerfile: Dockerfile
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      # PORT: 3000
      # DEBUG: True
      # SECRET_KEY:
      DB_HOST: db
      DB_USER: mariadb
      DB_PASSWORD: mariadb
      DB_DATABASE: cookbook
    env_file:
      - tokens.env
    volumes:
      - ./api:/app
  web:
    build: ./flutter
    ports:
      - 8080:80
    depends_on:
      - api
    environment:
      API_HOST: api
      API_PORT: 3000
    env_file:
      - tokens.env
  sonar-scanner:
    profiles:
      - full
      - sonar
    image: sonarsource/sonar-scanner-cli
    environment:
      SONAR_HOST_URL: "http://localhost:9000"
      SONAR_LOGIN: "sqp_6f984a61341493c85402c31cbd142b46eb1b21d8"
      SONAR_SCANNER_OPTS: "-Dsonar.projectKey=captain-cook"
    volumes:
      - ".:/usr/src"
    network_mode: "host"
