secrets:
  GOOGLE_CLIENT_ID:
    file: secrets/google_client_id
  GOOGLE_CLIENT_SECRET:
    file: secrets/google_client_secret
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cookbook
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
  api:
    build: ./api
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      # PORT: 3000
      DEBUG: True
      # SECRET_KEY:
      DB_HOST: db
      DB_USER: mariadb
      DB_PASSWORD: mariadb
      DB_DATABASE: cookbook
    volumes:
      - ./api:/app
    secrets:
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
  web:
    build: ./flutter
    ports:
      - 8080:80
    depends_on:
      - api
    environment:
      API_HOST: api
      API_PORT: 3000
