services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cookbook
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - default
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PORT: 3000
      DB_HOST: db
      DB_USER: mariadb
      DB_PASSWORD: mariadb
      DB_DATABASE: cookbook
    env_file:
      - tokens.env
    networks:
      - web
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cc-api.entrypoints=https"
      - "traefik.http.routers.cc-api.rule=Host(`captain-cook-api.big-sala.me`)"
      - "traefik.http.routers.cc-api.tls=true"
      - "traefik.http.routers.cc-api.tls.certresolver=http"
      - "traefik.http.services.cc-api.loadbalancer.server.port=3000"
      - "traefik.docker.network=web"
  web:
    build:
      context: ./flutter
      dockerfile: Dockerfile
      args:
        API_BASE_URL: "https://captain-cook-api.big-sala.me"
    restart: unless-stopped
    depends_on:
      - api
    env_file:
      - tokens.env
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cc-ui.entrypoints=https"
      # - "traefik.http.routers.cc-ui.rule=Host(`cloud.arne-kapell.de`)"
      - "traefik.http.routers.cc-ui.rule=Host(`captain-cook.big-sala.me`)"
      - "traefik.http.routers.cc-ui.tls=true"
      - "traefik.http.routers.cc-ui.tls.certresolver=http"
      - "traefik.docker.network=web"

volumes:
  db_data:
    driver: local
networks:
  web:
    external: true
