services:
  db:
    image: docker.io/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cookbook
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
  adminer:
    profiles:
      - full
      - adminer
    image: docker.io/adminer
    ports:
      - 3001:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: dracula
  api:
    build:
      context: ./api
      # dockerfile: Dockerfile
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    depends_on:
      - db
    restart: unless-stopped
    environment:
      DEBUG: "True"
      # PORT: 3000
      # DB_FORCE_RECREATE: True
      DB_HOST: db
      DB_USER: mariadb
      DB_PASSWORD: mariadb
      DB_DATABASE: cookbook
    # env_file:
    #   - tokens.env
    volumes:
      - ./api:/app
  web:
    build:
      context: ./flutter
      dockerfile: Dockerfile
      args:
        API_BASE_URL: "http://localhost:3000"
    ports:
      - 8080:80
    depends_on:
      - api
    restart: unless-stopped
    # env_file:
    #   - tokens.env
  maria-db-backup:
    container_name: maria-db-backup
    image: tiredofit/db-backup
    links:
      - db
    volumes:
      - ./backups:/backup
    environment:
      - DB_TYPE=mariadb
      - DB_HOST=db #??
      - DB_NAME=cookbook
      - DB_USER=mariadb
      - DB_PASS=mariadb
      - DB_DUMP_FREQ=720 # backup every 12h
      # - DB_DUMP_BEGIN=0000      # backup starts immediately
      - DB_CLEANUP_TIME=2.880 # clean backups they are older than 2 days
      - CHECKSUM=SHA1
      - COMPRESSION=GZ
      - SPLIT_DB=FALSE
      - CONTAINER_ENABLE_MONITORING=FALSE
    restart: always
    networks:
      - default

volumes:
  db_data:
    driver: local
