services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cookbook
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
    restart: unless-stopped
  adminer:
    profiles:
      - full
      - adminer
    image: adminer
    ports:
      - 3001:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: dracula
  api:
    build:
      context: ./api
      # dockerfile: Dockerfile
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    depends_on:
      - db
    restart: unless-stopped
    environment:
      # PORT: 3000
      # DEBUG: True
      # SECRET_KEY:
      DB_HOST: db
      DB_USER: mariadb
      DB_PASSWORD: mariadb
      DB_DATABASE: cookbook
    env_file:
      - tokens.env
    volumes:
      - ./api:/app
  web:
    build: ./flutter
    ports:
      - 8080:80
    depends_on:
      - api
    restart: unless-stopped
    environment:
      API_HOST: api
      API_PORT: 3000
    env_file:
      - tokens.env
